/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lpirawiutemqwefptznr"
export const supabaseUrl = "https://lpirawiutemqwefptznr.supabase.co"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY 